import { StyleSheet } from "react-native";
import { COLOR, FONT } from "@/constants/THEME";

export const typographyStyles = StyleSheet.create({
  _: {},
  display_lg: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 57,
    letterSpacing: -0.25,
    lineHeight: 64,
  },
  display_md: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 45,
    letterSpacing: 0,
    lineHeight: 52,
  },
  display_sm: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 36,
    letterSpacing: 0,
    lineHeight: 44,
  },
  headline_lg: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 32,
    letterSpacing: 0,
    lineHeight: 40,
  },
  headline_md: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 28,
    letterSpacing: 0,
    lineHeight: 36,
  },
  headline_sm: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 24,
    letterSpacing: 0,
    lineHeight: 32,
  },
  title_lg: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 22,
    letterSpacing: 0,
    lineHeight: 28,
  },
  title_md: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 16,
    letterSpacing: 0.15,
    lineHeight: 24,
  },
  title_sm: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  body_lg: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 16,
    letterSpacing: 0.5,
    lineHeight: 24,
  },
  body_md: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 14,
    letterSpacing: 0.25,
    lineHeight: 20,
  },
  body_sm: {
    fontFamily: FONT.RobotoRegular,
    fontWeight: "400",
    fontSize: 12,
    letterSpacing: 0.4,
    lineHeight: 16,
  },
  label_lg: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  label_lg_bold: {
    fontFamily: FONT.RobotoBold,
    fontWeight: "700",
    fontSize: 14,
    letterSpacing: 0.1,
    lineHeight: 20,
  },
  label_md: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  label_md_bold: {
    fontFamily: FONT.RobotoBold,
    fontWeight: "700",
    fontSize: 12,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
  label_sm: {
    fontFamily: FONT.RobotoMedium,
    fontWeight: "500",
    fontSize: 11,
    letterSpacing: 0.5,
    lineHeight: 16,
  },
});
